/* UtilityDesk.in V6.69 — global shell + sitewide rendering recovery. */
(function () {
  'use strict';
  const PDF_TOOLS=[['rotate-pdf','Rotate PDF','Rotate PDF pages clockwise or counter-clockwise','↻'],['rearrange-pages','Rearrange Pages','Reorder PDF pages into a new document','↕'],['pdf-to-images','PDF to Images','Convert PDF pages to image files','🖼️']];
  const DOC_TOOLS=[['joining-letter','Joining Letter','Create a professional joining letter','📄'],['increment-letter','Increment Letter','Create an employee salary increment letter','💰'],['promotion-letter','Promotion Letter','Create an employee promotion letter','📈'],['warning-letter','Warning Letter','Create a formal employee warning letter','⚠️'],['cover-letter','Cover Letter Generator','Create a tailored professional cover letter','✉️'],['exit-checklist','Exit Checklist','Prepare a complete employee exit checklist','☑️'],['resume-builder','Resume Builder','Build an ATS-friendly professional resume','📋'],['payslip','Payslip Generator','Create a professional monthly payslip','🧾']];
  function injectCss(){if(document.querySelector('link[data-ud-site-fix]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='/shared/site-fix.css';link.dataset.udSiteFix='1';document.head.appendChild(link)}
  function fixText(v){return v.replaceAll('`n','').replaceAll('â‚¹','₹').replaceAll('â€”','—').replaceAll('â€“','–').replaceAll('â€™','’').replaceAll('â€˜','‘').replaceAll('â€œ','“').replaceAll('â€','”').replaceAll('â€¦','…').replaceAll('â€¢','•').replaceAll('Ã—','×').replaceAll('Â©','©').replaceAll('Â°','°')}
  function repairLegacyMarkup(){const walker=document.createTreeWalker(document.documentElement,NodeFilter.SHOW_TEXT),nodes=[];let node;while((node=walker.nextNode()))nodes.push(node);nodes.forEach(textNode=>{const owner=textNode.parentElement;if(owner&&/^(SCRIPT|STYLE|NOSCRIPT)$/i.test(owner.tagName))return;let value=fixText(textNode.nodeValue||'');if(!value)return;const match=value.match(/^\s*section\s+class\s*=\s*(["'])([^"']+)\1\s*>\s*$/i);if(!match){if(value!==textNode.nodeValue)textNode.nodeValue=value;return}const parent=textNode.parentNode;if(!parent)return;const section=document.createElement('section');section.className=match[2];parent.insertBefore(section,textNode);let sibling=textNode.nextSibling;textNode.remove();while(sibling){const next=sibling.nextSibling;const boundary=sibling.nodeType===1&&(sibling.tagName.toLowerCase()==='section'||sibling.tagName.toLowerCase()==='footer'||/^(faq-section|content-section|related-section|cta-section|table-section|tool-section)$/i.test(sibling.className||''));if(boundary)break;section.appendChild(sibling);sibling=next}})}
  function addCard(prefix,item,bg){const [slug,title,desc,icon]=item,href='/'+prefix+'/'+slug+'/';const a=document.createElement('a');a.href=href;a.className='tool-card';a.dataset.title=title.toLowerCase();a.dataset.desc=desc.toLowerCase();a.innerHTML='<div class="tool-icon" style="background:'+bg+'">'+icon+'</div><div class="tool-card-body"><h3>'+title+'</h3><p>'+desc+'</p></div>';return a}
  function refreshCounts(){document.querySelectorAll('.category-block').forEach(block=>{const c=block.querySelector('.cat-count');if(c)c.textContent=block.querySelectorAll('.tool-card').length})}
  function repairPdfIndex(){if(location.pathname.replace(/index\.html$/,'')!=='/pdf-tools/')return;const grid=document.querySelector('.category-block[data-cat="client"] .tools-grid,.category-block[data-cat="browser"] .tools-grid');if(!grid)return;PDF_TOOLS.forEach(item=>{const href='/pdf-tools/'+item[0]+'/';if(!document.querySelector('.tool-card[href="'+href+'"]'))grid.appendChild(addCard('pdf-tools',item,'#dbe6fe'))});const n=document.querySelectorAll('.tool-card[href^="/pdf-tools/"]').length,count=document.getElementById('searchCount'),input=document.getElementById('searchInput');if(count)count.textContent=n+' tools available';if(input)input.placeholder='Search '+n+'+ tools...';const h=document.querySelector('.category-block[data-cat="convert"] h2');if(h&&h.firstChild)h.firstChild.nodeValue='🔄 Convert & Advanced ';refreshCounts()}
  function repairDocumentIndex(){if(location.pathname.replace(/index\.html$/,'')!=='/document-generators/')return;const blocks=[...document.querySelectorAll('.category-block')],block=blocks.find(b=>/hr|employment/i.test(b.textContent))||blocks[0],grid=block&&block.querySelector('.tools-grid');if(!grid)return;DOC_TOOLS.forEach(item=>{const href='/document-generators/'+item[0]+'/';if(!document.querySelector('.tool-card[href="'+href+'"]'))grid.appendChild(addCard('document-generators',item,'#fef3d6'))});const n=document.querySelectorAll('.tool-card[href^="/document-generators/"]').length,count=document.getElementById('searchCount'),input=document.getElementById('searchInput');if(count)count.textContent=n+' tools available';if(input)input.placeholder='Search '+n+'+ tools...';refreshCounts()}
  function repairHrIndex(){if(location.pathname.replace(/index\.html$/,'')!=='/hr/')return;const count=document.getElementById('searchCount'),input=document.getElementById('searchInput');if(count)count.textContent='23 tools available';if(input)input.placeholder='Search 23+ tools...'}
  function setupNavigation(){const header=document.querySelector('.ud-header');if(!header)return;const mobileMenu=document.querySelector('.ud-mobile-menu'),mobileToggle=document.querySelector('.ud-mobile-toggle'),dropdown=document.querySelector('.ud-nav-dropdown');if(mobileToggle&&mobileMenu)mobileToggle.addEventListener('click',()=>{mobileMenu.classList.toggle('active');mobileToggle.setAttribute('aria-expanded',mobileMenu.classList.contains('active')?'true':'false')});if(dropdown){const trigger=dropdown.querySelector('.ud-nav-dropdown-trigger');if(trigger)trigger.addEventListener('click',e=>{e.stopPropagation();dropdown.classList.toggle('active');trigger.setAttribute('aria-expanded',dropdown.classList.contains('active')?'true':'false')});document.addEventListener('click',e=>{if(!dropdown.contains(e.target)){dropdown.classList.remove('active');if(trigger)trigger.setAttribute('aria-expanded','false')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){dropdown.classList.remove('active');if(trigger)trigger.setAttribute('aria-expanded','false')}})}window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>20),{passive:true});const page=location.pathname.replace(/index\.html$/,'');document.querySelectorAll('.ud-nav-link,.ud-mobile-menu-link').forEach(link=>{const href=link.getAttribute('href');if(!href||!href.startsWith('/'))return;const target=href.endsWith('/')?href:href+'/';const active=page===target||(target!=='/'&&page.startsWith(target));link.classList.toggle('active',active);if(active)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current','page')})}
  function init(){injectCss();repairLegacyMarkup();repairPdfIndex();repairDocumentIndex();repairHrIndex();setupNavigation()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
}());
